#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.


echo "AZURE_TENANT_ID = $AZURE_TENANT_ID"
echo "AZURE_CLIENT_ID = $AZURE_CLIENT_ID"
echo "AZURE_CLIENT_SECRET = $AZURE_CLIENT_SECRET"

echo "MSI_ENDPOINT = $MSI_ENDPOINT"

echo "ARM_USE_MSI = $ARM_USE_MSI"
echo "ARM_MSI_ENDPOINT = $ARM_MSI_ENDPOINT"
echo "ARM_TENANT_ID = $ARM_TENANT_ID"
echo "ARM_SUBSCRIPTION_ID = $ARM_SUBSCRIPTION_ID"
echo "ARM_RESOURCE_GROUP_NAME = $ARM_RESOURCE_GROUP_NAME"

echo "ENVIRONMENT_ID = $ENVIRONMENT_ID"
echo "ENVIRONMENT_LOCATION = $ENVIRONMENT_LOCATION"
echo "ENVIRONMENT_SUBSCRIPTION = $ENVIRONMENT_SUBSCRIPTION"
echo "ENVIRONMENT_SUBSCRIPTION_ID = $ENVIRONMENT_SUBSCRIPTION_ID"
echo "ENVIRONMENT_RESOURCE_GROUP_ID = $ENVIRONMENT_RESOURCE_GROUP_ID"
echo "ENVIRONMENT_RESOURCE_GROUP_NAME = $ENVIRONMENT_RESOURCE_GROUP_NAME"
echo "ENVIRONMENT_ARTIFACTS = $ENVIRONMENT_ARTIFACTS"

echo "ENVIRONMENT_TYPE_ID = $ENVIRONMENT_TYPE_ID"
echo "ENVIRONMENT_TYPE_NAME = $ENVIRONMENT_TYPE_NAME"
echo "ENVIRONMENT_TYPE_IDENTITY = $ENVIRONMENT_TYPE_IDENTITY"
echo "ENVIRONMENT_TYPE_IDENTITY_TYPE = $ENVIRONMENT_TYPE_IDENTITY_TYPE"

echo "PROJECT_ID = $PROJECT_ID"
echo "PROJECT_NAME = $PROJECT_NAME"

echo "DEVCENTER_ID = $DEVCENTER_ID"
echo "DEVCENTER_NAME = $DEVCENTER_NAME"

echo "DEVCENTER_CONFIG_ID = $DEVCENTER_CONFIG_ID"
echo "DEVCENTER_CONFIG_NAME = $DEVCENTER_CONFIG_NAME"

echo "DEVCENTER_STORAGE_ID = $DEVCENTER_STORAGE_ID"
echo "DEVCENTER_STORAGE_NAME = $DEVCENTER_STORAGE_NAME"

echo "ACTION_ID = $ACTION_ID"
echo "ACTION_NAME = $ACTION_NAME"
echo "ACTION_HOST = $ACTION_HOST"
echo "ACTION_BASE_URL = $ACTION_BASE_URL"
echo "ACTION_PARAMETERS = $ACTION_PARAMETERS"
echo "ACTION_STORAGE = $ACTION_STORAGE"
echo "ACTION_TEMP = $ACTION_TEMP"
echo "ACTION_OUTPUT = $ACTION_OUTPUT"

echo "CATALOG = $CATALOG"
echo "CATALOG_NAME = $CATALOG_NAME"
echo "CATALOG_ITEM = $CATALOG_ITEM"
echo "CATALOG_ITEM_NAME = $CATALOG_ITEM_NAME"
echo "CATALOG_ITEM_TEMPLATE = $CATALOG_ITEM_TEMPLATE"
echo "CATALOG_ITEM_TEMPLATE_URL = $CATALOG_ITEM_TEMPLATE_URL"
echo "CATALOG_ITEM_TEMPLATE_URL_TOKEN = $CATALOG_ITEM_TEMPLATE_URL_TOKEN"