#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.


echo "AZURE_TENANT_ID = $AZURE_TENANT_ID"
echo "AZURE_CLIENT_ID = $AZURE_CLIENT_ID"
echo "AZURE_CLIENT_SECRET = $AZURE_CLIENT_SECRET"

echo "MSI_ENDPOINT = $MSI_ENDPOINT"

echo "ARM_USE_MSI = $ARM_USE_MSI"
echo "ARM_MSI_ENDPOINT = $ARM_MSI_ENDPOINT"
echo "ARM_TENANT_ID = $ARM_TENANT_ID"
echo "ARM_SUBSCRIPTION_ID = $ARM_SUBSCRIPTION_ID"
echo "ARM_RESOURCE_GROUP_NAME = $ARM_RESOURCE_GROUP_NAME"

echo "ADE_ENVIRONMENT_ID = $ADE_ENVIRONMENT_ID"
echo "ADE_ENVIRONMENT_LOCATION = $ADE_ENVIRONMENT_LOCATION"
echo "ADE_ENVIRONMENT_SUBSCRIPTION = $ADE_ENVIRONMENT_SUBSCRIPTION"
echo "ADE_ENVIRONMENT_SUBSCRIPTION_ID = $ADE_ENVIRONMENT_SUBSCRIPTION_ID"
echo "ADE_ENVIRONMENT_RESOURCE_GROUP_ID = $ADE_ENVIRONMENT_RESOURCE_GROUP_ID"
echo "ADE_ENVIRONMENT_RESOURCE_GROUP_NAME = $ADE_ENVIRONMENT_RESOURCE_GROUP_NAME"
echo "ADE_ENVIRONMENT_ARTIFACTS = $ADE_ENVIRONMENT_ARTIFACTS"

echo "ADE_ENVIRONMENT_TYPE_ID = $ADE_ENVIRONMENT_TYPE_ID"
echo "ADE_ENVIRONMENT_TYPE_NAME = $ADE_ENVIRONMENT_TYPE_NAME"
echo "ADE_ENVIRONMENT_TYPE_IDENTITY = $ADE_ENVIRONMENT_TYPE_IDENTITY"
echo "ADE_ENVIRONMENT_TYPE_IDENTITY_TYPE = $ADE_ENVIRONMENT_TYPE_IDENTITY_TYPE"

echo "ADE_PROJECT_ID = $ADE_PROJECT_ID"
echo "ADE_PROJECT_NAME = $ADE_PROJECT_NAME"

echo "ADE_DEVCENTER_ID = $ADE_DEVCENTER_ID"
echo "ADE_DEVCENTER_NAME = $ADE_DEVCENTER_NAME"

echo "ADE_DEVCENTER_CONFIG_ID = $ADE_DEVCENTER_CONFIG_ID"
echo "ADE_DEVCENTER_CONFIG_NAME = $ADE_DEVCENTER_CONFIG_NAME"

echo "ADE_DEVCENTER_STORAGE_ID = $ADE_DEVCENTER_STORAGE_ID"
echo "ADE_DEVCENTER_STORAGE_NAME = $ADE_DEVCENTER_STORAGE_NAME"

echo "ADE_ACTION_ID = $ADE_ACTION_ID"
echo "ADE_ACTION_NAME = $ADE_ACTION_NAME"
echo "ADE_ACTION_HOST = $ADE_ACTION_HOST"
echo "ADE_ACTION_BASE_URL = $ADE_ACTION_BASE_URL"
echo "ADE_ACTION_PARAMETERS = $ADE_ACTION_PARAMETERS"
echo "ADE_ACTION_STORAGE = $ADE_ACTION_STORAGE"
echo "ADE_ACTION_TEMP = $ADE_ACTION_TEMP"
echo "ADE_ACTION_OUTPUT = $ADE_ACTION_OUTPUT"

echo "ADE_CATALOG = $ADE_CATALOG"
echo "ADE_CATALOG_NAME = $ADE_CATALOG_NAME"
echo "ADE_CATALOG_ITEM = $ADE_CATALOG_ITEM"
echo "ADE_CATALOG_ITEM_NAME = $ADE_CATALOG_ITEM_NAME"
echo "ADE_CATALOG_ITEM_TEMPLATE = $ADE_CATALOG_ITEM_TEMPLATE"
echo "ADE_CATALOG_ITEM_TEMPLATE_URL = $ADE_CATALOG_ITEM_TEMPLATE_URL"
echo "ADE_CATALOG_ITEM_TEMPLATE_URL_TOKEN = $ADE_CATALOG_ITEM_TEMPLATE_URL_TOKEN"